Neptun/Models/FeedBack.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Neptun.Models
{
    public class FeedBack
    {
        [HiddenInput(DisplayValue = false)] public int Id { get; set; }

        [Display(Name = "Фамилия")]
        public string LastName { get; set; }

        [Required(ErrorMessage = "Обязательно для заполнения")]
        [Display(Name = "Имя")]
        public string FirstName { get; set; }

        [Phone(ErrorMessage = "Введите корректный телефонный номер")]
        [Display(Name = "Телефон")]
        public string PhoneNuber { get; set; }

        [Required(ErrorMessage = "Обязательно для заполнения")]
        [EmailAddress(ErrorMessage = "Введите корректный Email")]
        [Display(Name = "Email")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Обязательно для заполнения")]
        [MaxLength(1000, ErrorMessage = "Сообщение слишком длинное")]
        [Display(Name = "Сообщение")]
        [DataType(DataType.MultilineText)]
        public string Message { get; set; }

        [Display(Name = "Дата")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public DateTime ?Date { get; set; }

    }
}

Neptun/Controllers/FeedBacksController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;
using Neptun.Models;
using Neptun.Models.Email;
using Neptun.Persistence;

namespace Neptun.Controllers
{
    public class FeedBacksController : Controller
    {
        private DataContext db = new DataContext();

        // GET: FeedBacks
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Index([Bind(Include = "Id,LastName,FirstName,PhoneNuber,Email,Message")] FeedBack feedBack)
        {
            if (ModelState.IsValid)
            {
                feedBack.Date = DateTime.Today;
                db.FeedBacks.Add(feedBack);
                await db.SaveChangesAsync();
                await AutoEmailNotification(feedBack);

                return new HttpStatusCodeResult(System.Net.HttpStatusCode.OK);
            }

            return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
        }

        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> AdminInfo()
        {
            var feedBacks = await db.FeedBacks.ToListAsync();
            feedBacks.Reverse();
            return View(feedBacks);
        }

        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FeedBack feedBack = await db.FeedBacks.FindAsync(id);
            if (feedBack == null)
            {
                return HttpNotFound();
            }
            return View(feedBack);
        }

        [Authorize(Roles = "Admin")]
        [HttpPost, ActionName("Delete")]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            FeedBack feedBack = await db.FeedBacks.FindAsync(id);
            db.FeedBacks.Remove(feedBack);
            await db.SaveChangesAsync();
            return new HttpStatusCodeResult(System.Net.HttpStatusCode.OK);
        }

        private async Task AutoEmailNotification(FeedBack fb)
        {
            var smtp = new System.Net.Mail.SmtpClient("robots.1gb.ua", 25);

            var m = new MailMessage()
            {
                From = new MailAddress("tdneptun@neptun-odessa.com", "\"nepun-odessa.com\""),
                To = { new MailAddress("skalachev@soyuz-corp.com") },
                Subject = fb.Date?.ToString("dd.MM.yyyy", CultureInfo.InvariantCulture),
                Body = $"<h4>Вам написал {fb.FirstName} {fb.LastName}  {fb.Date?.ToString("dd.MM.yyyy", CultureInfo.InvariantCulture)}</h4>" +
                       $"<div><pre>Почта:\t{fb.Email}</pre></div>" +
                       $"<div><pre>Телефон:\t{fb.PhoneNuber}</pre></div>" +
                       $"<p><pre>Сообщение:\t{fb.Message}</pre></p>",
                IsBodyHtml = true
            };
            await smtp.SendMailAsync(m);
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> SendEmail([Bind(Include = "Email, Password, DestinationEmail, Header, Subject, Message")]EmailRespond respond)
        {
            if (!ModelState.IsValid)
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
            }

            var smtp = new System.Net.Mail.SmtpClient("smtp.gmail.com", 587)
            {
                EnableSsl = true,
                Credentials = new System.Net.NetworkCredential(respond.Email, respond.Password)
            };

            var m = new MailMessage()
            {
                From = new MailAddress(respond.Email, respond.Header),
                To = { new MailAddress(respond.DestinationEmail) },
                Subject = respond.Subject,
                Body = respond.Message
            };
            await smtp.SendMailAsync(m);
            return new HttpStatusCodeResult(System.Net.HttpStatusCode.OK);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Neptun/Views/FeedBacks/AdminInfo.cshtml
@model IEnumerable<Neptun.Models.FeedBack>

@{
    ViewBag.Title = "AdminInfo";
}
<div class="container">
    <h3 class="m-5">Обратная связь</h3>

    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.LastName) @Html.DisplayNameFor(model => model.FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Date)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PhoneNuber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Message)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.LastName) @Html.DisplayFor(modelItem => item.FirstName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Date)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PhoneNuber)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Message)
                </td>
                <td>
                    <button class="btn btn-danger" onclick="deleteItem(@item.Id)">Удалить</button>
                    <button type="button" style="display: none" class="btn btn-primary" data-toggle="modal" data-target="#Modal" 
                            onclick="openSendEmailModalWindow('@item.Email', '@item.FirstName', '@item.LastName', '@item.Date')">Ответить</button>
                </td>
            </tr>
        }
    </table>
    <div class="modal fade" id="Modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true" style="display: none">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="form-group row">
                        <label class="col-md-2" for="Email">Почта</label>
                        <div class="col-md-10">
                            <input class="form-control text-box single-line" id="Email" name="Email" type="email" value="" />
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-md-2" for="Password">Пароль</label>
                        <div class="col-md-10">
                            <input class="form-control text-box single-line" id="Password" name="Password" type="password" value="" />
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-md-2" for="DestinationEmail">Почта получателя</label>
                        <div class="col-md-10">
                            <input class="form-control text-box single-line" id="DestinationEmail" name="DestinationEmail" type="email" value="" />
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-md-2" for="Header">Заголовок</label>
                        <div class="col-md-10">
                            <input class="form-control text-box single-line" id="Header" name="Header" type="text" value="" />
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-md-2" for="Subject">Тема</label>
                        <div class="col-md-10">
                            <input class="form-control text-box single-line" id="Subject" name="Subject" type="text" value="" />
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-md-2" for="Message">Текст</label>
                        <div class="col-md-10">
                            <textarea  class="form-control" rows="8" id="Message" name="Message" type="text" value="" ></textarea>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button id="closeModal" type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
                    <button type="button" class="btn btn-primary" onclick="sendEmail()">Отправить</button>
                </div>
            </div>
        </div>
    </div>


</div>

@section Scripts{
    <script>
        function deleteItem(item) {
            var confirmDelete = confirm("Вы уверенны что хотите удалить эту запись?");
            if (confirmDelete) {
                $.ajax({
                    type: "POST",
                    url: "/FeedBacks/Delete",
                    data: {"Id": item},
                    success: function() {
                        window.location.replace("@Url.Action("AdminInfo", "FeedBacks")");
                    },
                    error: function(data) {
                        alert(data.x);
                    }
                });
            }
        };
        function openSendEmailModalWindow(destinationEmail, firstName, lastName, date) {
            document.getElementById("Header").value = "Ответ от завода \"Нептун\"";
            document.getElementById("Subject").value = "Ответ на запрос оставленый " + date.slice(3, 5) + "/" + date.slice(0, 2) + date.slice(5, 10) ;
            document.getElementById("DestinationEmail").value = destinationEmail;
            document.getElementById("Message").value = "Здравствуйте, " + firstName + " " + lastName + "! Спасибо за проявленный интерес к нашей продукции.";
        };
        function sendEmail(item) {

            var data = {
                Email: $('#Email').val().trim(),
                Password: $('#Password').val().trim(),
                DestinationEmail: $('#DestinationEmail').val().trim(),
                Header: $('#Header').val().trim(),
                Subject: $('#Subject').val().trim(),
                Message: $('#Message').val().trim()
            };
            $.ajax({
                type: "POST",
                url: "/FeedBacks/SendEmail",
                data: data,
                async: true,
                success: function () {;
                    alert("Ваше сообщение отправлено");
                    document.getElementById("closeModal").click();
                },
                error: function (data) {
                    alert("Сообщение не отправлено, извините. Попробуйте другой способ.");
                }
            });
        };
    </script>
    
    <style>

    </style>
}

Neptun/Views/FeedBacks/Delete.cshtml
@model Neptun.Models.FeedBack

@{
    ViewBag.Title = "Delete";
}
<div class="container">
    <h2>Delete</h2>

    <h3>Вы уверены что хотите удалить это сообщение?</h3>
    <div>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.LastName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.LastName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.FirstName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.FirstName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.PhoneNuber)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.PhoneNuber)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Email)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Email)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Message)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Message)
            </dd>

        </dl>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="Удалить" class="btn btn-default" /> |
                @Html.ActionLink("Вернуться к списку", "AdminInfo")
            </div>
        }
    </div>
</div>

Neptun/Views/FeedBacks/Index.cshtml
@model Neptun.Models.FeedBack

@{
    ViewBag.Title = "Нептун | Обратная связь - быстрый ответ на все ваши вопросы";
}

@section metatags
{
    <meta name="keywords" content="Обратная связь, связь" />
    <meta name="description" content='Торговый дом Одесского завода "Нептун". Вы можете свзязаться с нами по поводу заказа продукции или уточнения информаии' />
}

@section links
{
    <link rel="canonical" href="http://neptun-odessa.com/FeedBacks" />
}

<div class="container">
    @using (Html.BeginForm("Index", "FeedBacks", FormMethod.Post))
    {
        @Html.AntiForgeryToken(){
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <div class="well well-sm">
                            <form class="form-horizontal" method="post">
                                <fieldset>
                                    <legend class="text-center header">Обратная связь</legend>

                                    <div class="form-group row">
                                        <span class="col-md-2 text-center"><i class="bigicon"></i></span>
                                        <div class="col-md-8">
                                            @Html.EditorFor(model => Model.FirstName, new { htmlAttributes = new { @class = "form-control", placeholder = "Имя" } })
                                            @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <span class="col-md-2   text-center"><i class="bigicon"></i></span>
                                        <div class="col-md-8">
                                            @Html.EditorFor(model => Model.LastName, new { htmlAttributes = new { @class = "form-control", placeholder = "Фамилия" } })
                                            @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
                                        </div>
                                    </div>

                                    <div class="form-group row">
                                        <span class="col-md-2 text-center"><i class="bigicon"></i></span>
                                        <div class="col-md-8">
                                            @Html.EditorFor(model => Model.Email, new { htmlAttributes = new { @class = "form-control", placeholder = "Email" } })
                                            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                                        </div>
                                    </div>

                                    <div class="form-group row">
                                        <span class="col-md-2 text-center"><i class="bigicon"></i></span>
                                        <div class="col-md-8">
                                            @Html.EditorFor(model => Model.PhoneNuber, new { htmlAttributes = new { @class = "form-control", placeholder = "Телефон (не обязательно)" } })
                                            @Html.ValidationMessageFor(model => model.PhoneNuber, "", new { @class = "text-danger" })
                                        </div>
                                    </div>

                                    <div class="form-group row">
                                        <span class="col-md-2 text-center"><i class="bigicon"></i></span>
                                        <div class="col-md-8">
                                            @Html.EditorFor(model => Model.Message, new
                                            {
                                                htmlAttributes = new
                                                {
                                                    @class = "form-control",
                                                    type = "TextArea",
                                                    placeholder = "Введите свое сообщение, в ближайшее время мы с вами свяжемся",
                                                    rows = "7"
                                                }
                                            })
                                            @Html.ValidationMessageFor(model => model.Message, "", new { @class = "text-danger" })
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <div class="col-md-12 text-center">
                                            <button name="submitButton" type="submit" class="btn btn-primary btn-lg">Отправить</button>
                                        </div>
                                    </div>
                                </fieldset>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        }
    }

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")

    }
</div>