Neptun/Models/News.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Neptun.Models
{
    public class News
    {
        [HiddenInput(DisplayValue = false)]
        public int Id { get; set; }

        [Required(ErrorMessage = "Обязательно для заполнения")]
        [Display(Name = "Заголовок")]
        public string Title { get; set; }

        [Required(ErrorMessage = "Обязательно для заполнения")]
        [Display(Name = "Дата")]
        [DisplayFormat(DataFormatString = "{0:dd'/'MM'/'yyyy}", ApplyFormatInEditMode = true)]
        public DateTime Date { get; set; }

        [Required(ErrorMessage = "обязательно для заполнения")]
        [MaxLength(10000, ErrorMessage = "Допустимая длина превышена")]
        [Display(Name = "Описание")]
        [DataType(DataType.MultilineText)]
        public string Description { get; set; }
    }
}

Neptun/Controllers/CompanyController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Neptun.Models;
using Neptun.Models.ViewModels;
using Neptun.Persistence;

namespace Neptun.Controllers
{
    public class CompanyController : Controller
    {
        private DataContext db = new DataContext();

        // GET: Companies
        public async Task<ActionResult> Index()
        {
            var company = await db.Companies.FirstOrDefaultAsync();
            var employees = await db.Employees.ToListAsync();

            var contacts = new ContactsViewModel
            {
                Company = company,
                Employees = employees
            };
            return View(contacts);
        }

        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> AdminInfo()
        {
            var company = await db.Companies.FirstOrDefaultAsync();
            if (company is default(Company))
            {
                return Redirect("/Company/Create");
            }
            return View(company);
        }

        // GET: Companies/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Companies/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,PhoneNumber,Fax,Address,Email")] Company company)
        {
            if (ModelState.IsValid)
            {
                db.Companies.Add(company);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(company);
        }

        // GET: Companies/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Company company = await db.Companies.FindAsync(id);
            if (company == null)
            {
                return HttpNotFound();
            }
            return View(company);
        }

        // POST: Companies/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,PhoneNumber,Fax,Address,Email")] Company company)
        {
            if (ModelState.IsValid)
            {
                db.Entry(company).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(company);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Neptun/Controllers/NewsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Neptun.Models;
using Neptun.Persistence;
using Neptun.Models.ViewModels;
using Neptun.Servises;

namespace Neptun.Controllers
{
    public class NewsController : Controller
    {
        private DataContext db = new DataContext();

        // GET: News
        public async Task<ActionResult> Index(int? page)
        {
            const int itemsPerPage = 12;
            var currentPageIndex = page ?? 0;
            var pageCount = (int)Math.Ceiling((double)db.News.Count() / itemsPerPage);

            if (currentPageIndex < 0 || currentPageIndex >= pageCount)
            {
                return HttpNotFound();
            }

            var view = new NewsIndexViewModel(pageCount, currentPageIndex);
            var news = db.News.OrderByDescending(x => x.Date);
            view.News = await news.Skip(currentPageIndex * itemsPerPage).Take(itemsPerPage).ToListAsync();

            return View(view);
        }

        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> AdminInfo()
        {
            var news = await db.News.ToListAsync();
            return View(news.OrderByDescending(x => x.Date));
        }

        // GET: News/Details/5

        // GET: News/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: News/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,Title,Date,Description,Photo,HttpPostedFilePhoto")] NewsCreateEditViewModel newsViewModel)
        {
            if (ModelState.IsValid)
            {
                News news = newsViewModel;
                news.Photo = FilesOperations.SaveImg(newsViewModel.HttpPostedFilePhoto);
                db.News.Add(news);
                await db.SaveChangesAsync();
                return RedirectToAction("AdminInfo");
            }

            return View(newsViewModel);
        }

        // GET: News/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            News news = await db.News.FindAsync(id);
            if (news == null)
            {
                return HttpNotFound();
            }
            return View((NewsCreateEditViewModel)news);
        }

        // POST: News/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Title,Date,Description,Photo,HttpPostedFilePhoto")] NewsCreateEditViewModel newsViewModel)
        {

            if (ModelState.IsValid)
            {
                News news = newsViewModel;

                if (newsViewModel.HttpPostedFilePhoto != null && newsViewModel.HttpPostedFilePhoto.ContentLength > 0)
                {
                    FilesOperations.DeleteFile(news.Photo);
                    news.Photo = FilesOperations.SaveImg(newsViewModel.HttpPostedFilePhoto);
                }

                db.Entry(news).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("AdminInfo");
            }

            return View(newsViewModel);
        }

        // GET: News/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            News news = await db.News.FindAsync(id);
            if (news == null)
            {
                return HttpNotFound();
            }
            return View(news);
        }

        // POST: News/Delete/5
        [HttpPost, ActionName("Delete")]
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            News news = await db.News.FindAsync(id);
            FilesOperations.DeleteFile(news.Photo);
            db.News.Remove(news);
            await db.SaveChangesAsync();
            return RedirectToAction("AdminInfo");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Neptun/Views/News/AdminInfo.cshtml
@model IEnumerable<Neptun.Models.News>

@{
    ViewBag.Title = "AdminInfo";
}
<div class="container">
    <h2 class="m-5">Новости</h2>

    <a class="btn btn-success mb-2" href='@Url.Action("Create", "News")'>Добавить новость</a>

    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Date)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Date)
                </td>
                <td>
                    @Html.Raw(item.Description)
                </td>
                <td>
                    <a class="btn btn-warning" href='@Url.Action("Edit", "News", new { id = item.Id })'>Изменить</a>
                    <button class="btn btn-danger" onclick="deleteItem(@item.Id)">Удалить</button>
                </td>
            </tr>
        }

    </table>
</div>

@section Scripts{
    <script>
        function deleteItem(item) {
            var confirmDelete = confirm("Вы уверенны что хотите удалить эту запись?");
            if (confirmDelete) {
                $.ajax({
                    type: "POST",
                    url: "/News/Delete",
                    data: {"Id": item},
                    success: function() {
                        window.location.replace("@Url.Action("AdminInfo", "News")");
                    },
                    error: function(data) {
                        alert(data.x);
                    }
                });
            }
        };
    </script>
}

Neptun/Views/News/Create.cshtml
@model Neptun.Models.ViewModels.NewsCreateEditViewModel

@{
    ViewBag.Title = "Create";
}
<div class="container">
    <h3 style="padding-top:20px;">Добавить новость</h3>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.9/summernote-bs4.css" rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.9/summernote-bs4.js"></script>

    <style>
        .table-bordered td {
            border: 1px solid #000000;
        }
        header nav.navigation {
            display: none;
        }
    </style>

    @using (Html.BeginForm("Create", "News", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group row">
                @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group row">
                @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control", @Value = DateTime.Today.ToString("dd/MM/yyyy"), type = "date" } })
                    @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group row">
                @Html.LabelFor(model => model.Photo, htmlAttributes: new { @class = "col-md-2" })
                <div class="col-md-10">
                    <p>(jpg, jpeg, png, gif) </p>
                    @Html.TextBoxFor(model => model.HttpPostedFilePhoto, new { type = "file", value = "test" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Description)
                <div>
                    @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control", id = "summernote" } })
                    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                </div>
            </div>



            <div class="form-group">
                <div class="offset-md-2 col-md-10">
                    <input type="submit" value="Добавить" class="btn" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Вернуться с списку", "AdminInfo")
    </div>

    <script>
        $('#summernote').summernote({
            placeholder: 'Введите описание продукции',
            tabsize: 2,
            height: 100
        });
        $('.dropdown-toggle').dropdown();
    </script>

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }
</div>

Neptun/Views/News/Delete.cshtml
@model Neptun.Models.News

@{
    ViewBag.Title = "Delete";
}
<div class="container">
    <h3>Вы уверены что хотите удалить эту новость?</h3>
    <div>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Title)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Title)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Date)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Date)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Description)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Description)
            </dd>

        </dl>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="Удалить" class="btn btn-default" /> |
                @Html.ActionLink("Вернуться к списку", "AdminInfo")
            </div>
        }
    </div>
</div>

Neptun/Views/News/Edit.cshtml
@model Neptun.Models.ViewModels.NewsCreateEditViewModel

@{
    ViewBag.Title = "Edit";
}
<div class="container">
    <h3>Изменить</h3>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.9/summernote-bs4.css" rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.9/summernote-bs4.js"></script>

    <style>
        .table-bordered td {
            border: 1px solid #000000;
        }
        header nav.navigation {
            display: none;
        }
    </style>

    @using (Html.BeginForm(Html.BeginForm("Edit", "News", FormMethod.Post, new { enctype = "multipart/form-data" })))
    {
        @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group row">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group row">
            @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "col-md-2" })

            <div class="col-md-10">
                @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control", @Value = Model.Date.ToString("dd/MM/yyyy"), type = "date" } })

                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
            </div>


        </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Description)
                <div>
                    @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control", id = "summernote" } })
                    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group row">
                @Html.LabelFor(model => model.Photo, htmlAttributes: new { @class = "col-md-2" })
                <div class="col-md-10">
                    @Html.HiddenFor(model => model.Photo)
                    <p>(jpg, jpeg, png, gif) </p>
                    @Html.TextBoxFor(model => model.HttpPostedFilePhoto, new { type = "file", value = "photo" })
                </div>
            </div>

            <div class="form-group">
                <div class="offset-md-2 col-md-10">
                    <input type="submit" value="Сохранить" class="btn" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Вернуться к списку", "AdminInfo")
    </div>

    <script>
        $('#summernote').summernote({
            placeholder: 'Введите описание продукции',
            tabsize: 2,
            height: 100
        });
        $('.dropdown-toggle').dropdown();
    </script>

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }
</div>

Neptun/Views/News/Index.cshtml
@using Neptun.Models.Enum
@model Neptun.Models.ViewModels.NewsIndexViewModel

@{
    Layout = "";

    var leftArrow = Model.CurrentPage != 0 ? "" : "not-active";
    var rigthArrow = Model.CurrentPage != Model.PageCount - 1 ? "" : "not-active";
}


<!DOCTYPE html>
<html lang="ru">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="/Content/header.css" type="text/css">
    <link rel="stylesheet" href="/Content/news.css" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
    <meta name="keywords" content="Новости, Что нового" />
    <meta name="description" content='Что нового в торговом доме Одесского завода "Нептун". Свежие новости, новая продукция и услуги, которые уже доступны у нас.' />
    <link rel="icon" href="/favicon.ico" />
    <link rel="canonical" href="http://neptun-odessa.com/News" />
    <title>"Нептун | Новости - узнайте что у нас нового"</title>
</head>

<body>
    <header>
        <div class="header-container">
            <input type="checkbox" id="menu-checkbox">
            <nav>
                <label for="menu-checkbox" class="toggle-button" data-open="МЕНЮ" data-close="ЗАКРЫТЬ"></label>
                <ul class="main-menu">
                    <li>
                        <a href="@Url.Action("Index", "Home")">ГЛАВНАЯ</a>
                    </li>
                    <li class="dropdown">
                        <label for="dropdown-checkbox" id="#dropdown-label">ПРОДУКЦИЯ</label>
                        <input type="checkbox" id="dropdown-checkbox">
                        <div>
                            <ul>
                                <li>
                                    <a href="@Url.Action("Index", "Productions")">Вся продукция</a>
                                </li>
                                <hr>
                                <li>
                                    <a href="@Url.Action("Index", "Productions", new {productType = ProductType.HfProcessing})">ВЧ Обработка</a>
                                </li>
                                <li>
                                    <a href="@Url.Action("Index", "Productions", new {productType = ProductType.HfCommunication})">ВЧ Связь</a>
                                </li>
                                <li>
                                    <a href="@Url.Action("Index", "Productions", new {productType = ProductType.HfProtection})">ВЧ Защита</a>
                                </li>
                                <li>
                                    <a href="@Url.Action("Cabinets", "Productions")">Шкафы</a>
                                </li>
                                <hr>
                                <li>
                                    <a href='@Url.Action("Index", "Productions", new {productType = ProductType.Cleaning})'>Очистные сооружения</a>
                                </li>
                                <hr>
                                <li>
                                    <a href="@Url.Action("Index", "Productions", new {productType = ProductType.Other})">Прочее</a>
                                </li>
                            </ul>
                        </div>
                    </li>
                    <li>
                        <a href="@Url.Action("Index", "News")">НОВОСТИ</a>
                    </li>
                    <li>
                        <a href="@Url.Action("Index", "Company")">КОНТАКТЫ</a>
                    </li>
                    <li>
                        <a href="" onclick="window.open('/Pdf/Reference.pdf','_blank');">РЕФЕРЕНС</a>
                    </li>
                </ul>
            </nav>
        </div>
    </header>
    <main>
        <div class="page-container">
            <section class="top">
                <h1>Новости</h1>
                <p id="date"></p>
            </section>
            <section class="all-news">
                @foreach (var item in Model.News)
                {
                    <div class="news-box">
                        <div class="news-image">
                            <img src="@item.Photo" alt="@Html.DisplayFor(modelItem => item.Title)">
                        </div>
                        <div class="description">
                            <h2>@item.Title</h2>
                            <p> @Html.Raw(item.Description)</p>
                            <p class="date">@item.Date.ToString("dd/MM/yyyy")</p>
                        </div>
                    </div>
                }
            </section>
            @if (Model.PageCount > 1)
            {
                <section class="pagination">
                    <ul>
                        <li class="@leftArrow">
                            <a class="prev" href="@Url.Action("Index", "News", new { page = Model.CurrentPage - 1})">&lsaquo;</a>
                        </li>
                        @for (var i = 1; i < Model.PageCount + 1; i++)
                        {
                            var pageActive = Model.CurrentPage == i - 1 ? "current" : "";
                            <li class="@pageActive">
                                <a href="@Url.Action("Index", "News", new {page = i - 1})">@i</a>
                            </li>
                        }
                        <li class="@rigthArrow">
                            <a class="next" href="@Url.Action("Index", "News", new { page = Model.CurrentPage + 1 })">&rsaquo;</a>
                        </li>
                    </ul>
                </section>
            }
        </div>
    </main>
    <footer>
        <div class="page-container">
            <h4>Все права на торговую марку принадлежат ООО "Торговый дом Одесского завода "Нептун"</h4>
        </div>
    </footer>
</body>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="/Scripts/user/header-script.js" type="text/javascript"></script>
<script src="/Scripts/user/news.js" type="text/javascript"></script>

</html>