Neptun/Models/Production.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Neptun.Models.Enum;

namespace Neptun.Models
{
    public class Production
    {
        [HiddenInput(DisplayValue = false)]
        public int Id { get; set; }

        [Required(ErrorMessage = "Обязательно для заполнения")]
        [Display(Name = "Название")]
        [MaxLength(300, ErrorMessage = "Допустимая длина превышена")]
        public string Title { get; set; }

        [Required(ErrorMessage = "Обязательно для заполнения")]
        [MaxLength(50000, ErrorMessage = "Допустимая длина превышена")]
        [Display(Name = "Описание")]
        [AllowHtml]
        [DataType(DataType.MultilineText)]
        public string Description { get; set; }

        [Display(Name = "Полное описание в PDF")]
        public string FullDescriptionPdf { get; set; }

        [Display(Name = "Название кнопки для описания")]
        public string ButtonDescriptionName { get; set; }

        [Required(ErrorMessage = "Обязательно для заполнения")]
        [Display(Name = "Тип продукции")]
        public ProductType ProductType { get; set; }

        [Display(Name = "Фото")]
        public string Photo { get; set; }

        [Display(Name = "Title")]
        [MaxLength(100, ErrorMessage = "Допустимая длина 100 превышена")]
        public string PageTitle { get; set; }

        [Display(Name = "Description")]
        [MaxLength(1000, ErrorMessage = "Допустимая длина 300 превышена")]
        public string PageDescription { get; set; }

        [Display(Name = "Keywords")]
        [MaxLength(1000, ErrorMessage = "Допустимая длина 300 превышена")]
        public string PageKeywords { get; set; }
    }
}

Neptun/Controllers/ProductionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Neptun.Models;
using Neptun.Models.Enum;
using Neptun.Models.ViewModels;
using Neptun.Persistence;
using Neptun.Servises;

namespace Neptun.Controllers
{
    public class ProductionsController : Controller
    {
        private DataContext db = new DataContext();

        // GET: Productions
        public async Task<ActionResult> Index(int? page, ProductType? productType)
        {
            const int itemsPerPage = 12;
            var currentPageIndex = page ?? 0;
            var pageCount = productType == null ? db.Productions.Count() : db.Productions.Count(x => x.ProductType == productType);
            pageCount = (int) Math.Ceiling((double) pageCount / itemsPerPage);

            if (pageCount == 0) return Redirect("/Productions/EmptyProductionPage");

            if (currentPageIndex < 0 || currentPageIndex >= pageCount)
            {
                return HttpNotFound();
            }

            var view = new ProductIndexViewModel(pageCount, currentPageIndex, productType);

            var query = db.Productions.OrderBy(x => x.Id).Select(x => new ProductionListViewModel
            {
                Id = x.Id,
                Title = x.Title,
                FullDescriptionPdf = x.FullDescriptionPdf,
                Photo = x.Photo,
                ButtonDescriptionName = x.ButtonDescriptionName,
                ProductType = x.ProductType
            });

            if (productType != null)
            {
                query = query.Where(x => x.ProductType == productType);
            }

            view.Products = await query.Skip(currentPageIndex * itemsPerPage).Take(itemsPerPage).ToListAsync();

            return View(view);
        }

        public ActionResult EmptyProductionPage()
        {
            return View();
        }

        public ActionResult Cabinets()
        {
            return View();
        }

        public ActionResult TreatmentFacilities()
        {
            return View();
        }

        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> AdminInfo()
        {
            return View(await db.Productions.Select(x => new ProductionListViewModel
            {
                Id = x.Id,
                Title = x.Title,
                FullDescriptionPdf = x.FullDescriptionPdf,
                Photo = x.Photo,
                ButtonDescriptionName = x.ButtonDescriptionName,
                ProductType = x.ProductType
            }).ToListAsync());
        }

        public async Task<ActionResult> Info(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var production = await db.Productions.FindAsync(id);
            if (production == null)
            {
                return HttpNotFound();
            }

            //if (production.ProductType == ProductType.Cleaning) return RedirectToAction(production.PageDescription);

            return View(production);

        }

        // GET: Productions/Details/5
        public ActionResult DisplayPdf(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Production production = db.Productions.Find(id);
            if (string.IsNullOrEmpty(production?.ButtonDescriptionName) || production.FullDescriptionPdf.Length == 0)
            {
                return HttpNotFound();
            }
            var pdfPath = System.Web.HttpContext.Current.Server.MapPath(production.FullDescriptionPdf);

            if (System.IO.File.Exists(pdfPath)) HttpNotFound();

            var fileContents = System.IO.File.ReadAllBytes(pdfPath);

            return new FileContentResult(fileContents, "application/pdf");
        }

        public ActionResult DisplayPdfFromFile(string path)
        {
            var pdfPath = System.Web.HttpContext.Current.Server.MapPath(path);

            if (System.IO.File.Exists(pdfPath)) HttpNotFound();

            var fileContents = System.IO.File.ReadAllBytes(pdfPath);

            return new FileContentResult(fileContents, "application/pdf");
        }

        // GET: Productions/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Productions/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(
            [Bind(Include = "Id,Title,Description,FullDescriptionPdf,ButtonDescriptionName,ProductType,Photo, HttpPostedFilePhoto, HttpPostedFilePdf," +
                            "PageTitle, PageDescription, PageKeywords")]
            ProductionCreateEditViewModel productionViewModel)
        {
            if (ModelState.IsValid)
            {
                Production production = productionViewModel;
                production.Photo = FilesOperations.SaveImg(productionViewModel.HttpPostedFilePhoto);
                if (!string.IsNullOrEmpty(production.ButtonDescriptionName))
                    production.FullDescriptionPdf = FilesOperations.SavePdf(productionViewModel.HttpPostedFilePdf);

                db.Productions.Add(production);
                await db.SaveChangesAsync();
                return RedirectToAction("AdminInfo");
            }

            return View(productionViewModel);
        }

        // GET: Productions/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Production production = await db.Productions.FindAsync(id);
            if (production == null)
            {
                return HttpNotFound();
            }

            return View((ProductionCreateEditViewModel)production);
        }

        // POST: Productions/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(
            [Bind(Include = "Id,Title,Description,FullDescriptionPdf,ButtonDescriptionName,ProductType,Photo, HttpPostedFilePhoto, HttpPostedFilePdf," +
                            "PageTitle, PageDescription, PageKeywords")]
            ProductionCreateEditViewModel productionViewModel)
        {
            if (ModelState.IsValid)
            {
                Production production = productionViewModel;

                if (productionViewModel.HttpPostedFilePhoto != null && productionViewModel.HttpPostedFilePhoto.ContentLength > 0)
                {
                    FilesOperations.DeleteFile(production.Photo);
                    production.Photo = FilesOperations.SaveImg(productionViewModel.HttpPostedFilePhoto);
                }


                if (!string.IsNullOrEmpty(productionViewModel.ButtonDescriptionName))
                {
                    if (productionViewModel.HttpPostedFilePdf != null && productionViewModel.HttpPostedFilePdf.ContentLength > 0)
                    {
                        FilesOperations.DeleteFile(production.FullDescriptionPdf);
                        production.FullDescriptionPdf = FilesOperations.SavePdf(productionViewModel.HttpPostedFilePdf);
                    }
                }
                else FilesOperations.DeleteFile(production.FullDescriptionPdf);

                db.Entry(production).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("AdminInfo");
            }

            return View(productionViewModel);
        }

        // GET: Productions/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var production = await db.Productions.FindAsync(id);
            if (production == null)
            {
                return HttpNotFound();
            }

            return View(production);
        }

        // POST: Productions/Delete/5
        [HttpPost, ActionName("Delete")]
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            var production = await db.Productions.FindAsync(id);
            FilesOperations.DeleteFile(production.Photo);
            FilesOperations.DeleteFile(production.FullDescriptionPdf);
            db.Productions.Remove(production);
            await db.SaveChangesAsync();
            return RedirectToAction("AdminInfo");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }

            base.Dispose(disposing);
        }
    }
}

Neptun/Views/Productions/AdminInfo.cshtml
@model IEnumerable<Neptun.Models.ViewModels.ProductionListViewModel>

@{
    ViewBag.Title = "AdminInfo";
}
<div class="container">
    <h2 class="m-5">Работники</h2>

    <a class="btn btn-success mb-2" href='@Url.Action("Create", "Productions")'>Добавить продукцию</a>
    
    <a class="btn btn-secondary mb-2" href='@Url.Action("Index", "Productions")'>К виду пользователя</a>

    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                <text>PDF</text>
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ProductType)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Title)
                </td>
                <td>
                    @if (!string.IsNullOrEmpty(item.ButtonDescriptionName))
                    {
                        <a href='@Url.Action("DisplayPdf", "Productions", new {id = item.Id})' Onclick="window.open('@Url.Action("DisplayPdf", "Productions", new {id = item.Id})', target='_blank')">@Html.DisplayFor(modelItem => item.ButtonDescriptionName)</a>
                    }
                    else
                    {
                        <p>Нету</p>
                    }
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ProductType);
                </td>
                <td>
                    <a class="btn btn-warning" href='@Url.Action("Edit", "Productions", new { id = item.Id })'>Изменить</a>
                    <button class="btn btn-danger" onclick="deleteItem(@item.Id)">Удалить</button>
                    <a class="btn btn-info" href='@Url.Action("Info", "Productions", new { id = item.Id })'>Описание</a>
                </td>
            </tr>
        }

    </table>
</div>

@section Scripts{
    <script>
        function deleteItem(item) {
            var confirmDelete = confirm("Вы уверенны что хотите удалить эту запись?");
            if (confirmDelete) {
                $.ajax({
                    type: "POST",
                    url: "/Productions/Delete",
                    data: {"Id": item},
                    success: function() {
                        window.location.replace("@Url.Action("AdminInfo", "Productions")");
                    },
                    error: function(data) {
                        alert(data.x);
                    }
                });
            }
        };
    </script>
}

Neptun/Views/Productions/Cabinets.cshtml
@{
    ViewBag.Title = "Нептун | Продуция | Шкафы";
}

@section metatags
{
    <meta name="keywords" content="ШРЗиА, шкаф учета, ВРУ, ящики вводно-учетные, шкафы распределительные, ЩО, ЯВУ, ШНВА, ШОН" />
    <meta name="description" content="Мы предлагаем комплекс аппаратуры, позволяющей без особых затрат выполнить
          модернизацию подстанций с переводом средств РЗА на современную базу.
          Модернизация существующего оборудования может выполняться на базе оборудования установленного
          в шкафы со степенью защиты и перечнем комплектации, определяемой заказчиком." />
}

@section links
{
    <link rel="canonical" href="http://neptun-odessa.com/Productions/Cabinets" />
}

<style>
    h5 {
        display: list-item;
        list-style-type: disc;
        list-style-position: inside;
    }
</style>
<div class="container mt-5">
    <h2 class="text-center mb-5">Шкафы ШРЗиА , ШОН, шкафы наружной установки , щитки этажные</h2>
    <div class="row mb-1">
        <div class="col-lg-3 d-none d-lg-block">
            <img class="embed-responsive pb-5" src="/Pictures/Cabinets/1.jpg">
            <img class="embed-responsive pb-5" src="/Pictures/Cabinets/2.jpg">
            <img class="embed-responsive pb-5" src="/Pictures/Cabinets/3.jpg">
            <img class="embed-responsive pb-5" src="/Pictures/Cabinets/4.jpg">
            <img class="embed-responsive pb-5" src="/Pictures/Cabinets/5.jpg">
            <img class="embed-responsive pb-5" src="/Pictures/Cabinets/6.jpg">
            <img class="embed-responsive pb-5" src="/Pictures/Cabinets/7.jpg">
        </div>
        <article class="col-lg-9">
            <h3 class="pb-3">Предлагаем к поставке следующую продукцию:</h3>
            <h5>Шкафы релейной защиты и автоматики (ШРЗиА)</h5>
            <p>
                На базе микропроцессорных устройства фирм AREVA, ABB, Siemens, General Electric (и т.д. по желанию
                заказчика) предназначены для быстрой и селективной защиты от коротких замыканий в трансформаторах,
                электродвигателях и генераторах, а также других объектов, подключаемых к энергосистеме с двух
                сторон.
            </p>
            <h5>Низковольтные комплектные устройств общего применения</h5>
            <p>РТЗО-88, ВРУ, ЩО, ЯВУ, ЩКН, ПР11, ЩС, ЯЗН, ЯЗВ, ШНВА</p>
            <h5>Шкаф учета электроэнергии типа ШУУ-1-УХЛ 1</h5>
            <p>
                Предназначен для создания автоматизированных систем коммерческого учета электроэнергии (АСКУЭ).
                Предусмотрена возможность эксплуатации в районах с холодным климатом.
            </p>
            <h5>Блоки резервного питания(БРП)</h5>
            <p>
                Предназначены для резервного питания счетчиков в шкафах учета электроэнергии. Предусмотрено питание
                до
                12-ти счетчиков размещенных в шкафу учета.
            </p>
            <h5>НКУ ЩО 07</h5>
            <p>
                Предназначены для приёма и распределения электрической энергии трёхфазного тока частотой 50 Гц
                номинальным напряжением до 0,66 кВ. и защиты отходящих линий от перегрузки и токов короткого замыкания.

            </p>
            <h5>ВРУ (Вводно-распределительные устройства)</h5>
            <p>
                Предназначены для приёма, распределения и учёта электроэнергии в сетях 380/220В трёхфазного переменного
                тока частоты 50 Гц, а также для защиты линий при перегрузках и коротких замыканиях.
            </p>
            <h5>Ящики вводно-учётные типа ЯВУ</h5>
            <p>
                Предназначены для приёма учёта активной электроэнергии напряжением 380 В трёхфазного переменного тока
                частотой
                50 Гц систем с глухо-заземлённой нейтралью, а также для защиты отходящих линий при перегрузках и токах
                короткого
                замыкания
            </p>
            <h5>Шкафы распределительные силовые СПА–77</h5>
            <p>
                Предназначены для распределения электрической энергии трёхфазного переменного тока частотой 50 Гц и
                применяются
                в электроустановках промышленных предприятий. Шкафы СПА–77 предназначены для установки в электрощитовых
                помещениях.
            </p>
            <h5>Устройства автоматического переключения питания на резерв типа АВР</h5>
            <p>
                Предназначены для восстановления питания потребителей путём автоматического включения резервного
                источника
                питания при отключении рабочего источника питания, приводящего к обесточиванию электроустановок
                потребителя
                напряжением до 660В, переменного тока частотой 50Гц или 60Гц, а также предусматривается для
                автоматического
                включения резервного оборудования при отключении рабочего оборудования, приводящем к нарушению
                нормального
                технологического процесса.
            </p>
            <h5>Вводно-распределительные устройства типа ВРУ – М</h5>
            <p>
                Предназначены для приёма, распределения и учёта электроэнергии в сетях 380/220В трёхфазного переменного
                тока
                частоты 50 Гц, в сетях с глухозаземлённой нейтралью, также для защиты линий при перегрузках и коротких
                замыканиях для нечастых оперативных включений и отключений. ВРУ - М используется для электроснабжения
                потребителей по однолучевой схеме с единовременной нагрузкой не более 160 кВА.
            </p>

            <h5>Пункты распределительные серии ПР11</h5>
            <p>
                Предназначены для приёма и распределения электрической энергии, защиты электрических установок
                напряжением
                380/220 В переменного тока частотой 50 Гц при перегрузках и коротких замыканиях, а также нечастых (не
                более 6
                раз в час) включений и отключений электрических цепей и пусков асинхронных электродвигателей.
            </p>
            <h5>Шкафы распределительные силовые СПА–77</h5>
            <p>
                Предназначены для распределения электрической энергии трёхфазного переменного тока частотой 50 Гц и
                применяются в электроустановках промышленных предприятий. Шкафы СПА–77 предназначены для установки в
                электрощитовых помещениях.

            </p>
            <h5>Устройства автоматического переключения питания на резерв типа АВР</h5>
            <p>
                Предназначены для восстановления питания потребителей путём автоматического включения резервного
                источника питания при отключении рабочего источника питания, приводящего к обесточиванию
                электроустановок потребителя напряжением до 660В, переменного тока частотой 50Гц или 60Гц, а также
                предусматривается для автоматического включения резервного оборудования при отключении рабочего
                оборудования, приводящем к нарушению нормального технологического процесса.
            </p>
            <h5>Щитки этажные серии ЩС</h5>
            <p>
                Предназначены для учёта и распределения электрической энергии однофазного переменного тока напряжением
                220 В частотой 50 Гц и трёхфазного переменного тока напряжением 380/220 В частотой 50 Гц, а также для
                защиты групповых квартирных линий от перегрузки, токов короткого замыкания и недопустимых токов утечки
                на землю.
            </p>
            <h5>Шкафы отбора напряжения ШОН серии 300</h5>
            <p>Предназначены для:</p>
            <ul>
                <li>
                    ШОН-301С - для отбора напряжения от конденсаторов связи СМР-110/√3-6,и
                    СМР-166/√3-14 для линии электропередачи на 220, 330 и 500 кВ;
                </li>
                <li>
                    ШОН-302С - для отбора напряжения от конденсаторов связи СМР-66/√3-4,4 для линии электропередачи 110,
                    150, 220 кВ, с конденсаторами связи СМР-110/√3-2,2 для линии электропередачи 110, 220 кВ;
                </li>
                <li>
                    ШОН-303П - для отбора напряжения от конденсаторов связи СМР-20/√3-107 для линии электропередачи 35
                    кВ, с конденсаторами связи СМР-110/√3-6,4 для линии электропередачи 110, 220, 330 кВ, с
                    конденсаторами связи СМР-20/√3-35 для линии электропередачи 35, 110, 150 кВ;
                </li>
                <li>
                    ШОН-304П - для отбора напряжения от конденсаторов связи СМП-110/√3-6,4 для линии электропередачи
                    на 110, 150, и 220 кВ и конденсаторами связи СММ-20/√3-35 для линии электропередачи 35 кВ;
                </li>
                <li>
                    ШОН-305П - для отбора напряжения от конденсаторов связи СМП-110/√3-6,4 для линии электропередачи на
                    110, 150, и 220 кВ и конденсаторами связи СММ-20/√3-35 для линии электропередачи 35 кВ;
                </li>
            </ul>
            <input type="button" class="btn btn-info" onClick="window.open('@Url.Action("DisplayPdfFromFile", "Productions", new {path = "/Pdf/Catalog.pdf"})', target = '_blank')" value="Смотреть каталог" />
        </article>
    </div>
    <div class="cooperation-container">
        <section class="cooperation">
            <a href="/Company#feedback">
                <img src="/Pictures/Cooperation.png" alt="Торговый дом Нептун">
                <article>
                    <p>
                        Задайте интересующие вопросы и в ближайшее время мы свяжемся с вами.
                    </p>
                </article>
            </a>
        </section>
    </div>
</div>

Neptun/Views/Productions/Create.cshtml
@model Neptun.Models.ViewModels.ProductionCreateEditViewModel

@{
    ViewBag.Title = "Create";
}

<style>
    header nav.navigation {
        display: none;
    }
</style>

<div class="container">
    <h2>Добавить</h2>
    <div>
        @Html.ActionLink("Назад", "AdminInfo")
    </div>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.9/summernote-bs4.css" rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.9/summernote-bs4.js"></script>

    <style>
        .table-bordered td {
            border: 1px solid #000000;
        }
    </style>

    @using (Html.BeginForm(Html.BeginForm("Create", "Productions", FormMethod.Post, new { enctype = "multipart/form-data" })))
    {
        @Html.AntiForgeryToken()


        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group row">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description)
            <div>
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control", id = "summernote" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group row">
            @Html.LabelFor(model => model.ButtonDescriptionName, htmlAttributes: new { @class = "col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ButtonDescriptionName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ButtonDescriptionName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group row">
            @Html.LabelFor(model => model.FullDescriptionPdf, htmlAttributes: new { @class = "col-md-2" })
            <div class="col-md-10">
                <p>(pdf) </p>
                @Html.TextBoxFor(model => model.HttpPostedFilePdf, new { type = "file", value = "test" })
            </div>
        </div>

        <div class="form-group row">
            @Html.LabelFor(model => model.ProductType, htmlAttributes: new { @class = "col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.ProductType, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ProductType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group row">
            @Html.LabelFor(model => model.Photo, htmlAttributes: new { @class = "col-md-2" })
            <div class="col-md-10">
                <p>(jpg, jpeg, png, gif) </p>
                @Html.TextBoxFor(model => model.HttpPostedFilePhoto, new { type = "file", value = "test" })
            </div>
        </div>

        <div class="form-group row">
            @Html.LabelFor(model => model.PageTitle, htmlAttributes: new { @class = "col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PageTitle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PageTitle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group row">
            @Html.LabelFor(model => model.PageDescription, htmlAttributes: new { @class = "col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PageDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PageDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group row">
            @Html.LabelFor(model => model.PageKeywords, htmlAttributes: new { @class = "col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PageKeywords, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PageKeywords, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="pl-5 col-md-10">
                <input type="submit" value="Добавить" class="btn" />
            </div>
        </div>

    }

    <div>
        @Html.ActionLink("Вернуться к списку", "AdminInfo")
    </div>

    <script>
        $('#summernote').summernote({
            placeholder: 'Введите описание продукции',
            tabsize: 2,
            height: 100
        });
        $('.dropdown-toggle').dropdown();
    </script>

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }
</div>

Neptun/Views/Productions/DisplayPdf.cshtml
@{
    ViewBag.Title = "Документ PDF";
}

<h2>DisplayPdf</h2>

Neptun/Views/Productions/EmptyProductionPage.cshtml
@{
    ViewBag.Title = "EmptyPage";
}

<div class="container mt-5">
    <p class="font-italic">Извините, в данном разделе еще нет продукции, в ближайшее время она будет добавленна</p>
</div>

Neptun/Views/Productions/Info.cshtml
@using Neptun.Models.Enum
@model Neptun.Models.Production


@{
    var title = string.IsNullOrEmpty(Model.PageTitle) ? Model.Title : Model.PageTitle;
    ViewBag.Title = "Нептун | Продукция | " + title;
    var canonical = "http://neptun-odessa.com/Productions/Info/" + Model.Id;
}

@section metatags
{
    <meta name="keywords" content="@Model.PageKeywords" />
    <meta name="description" content="@Model.PageDescription" />
}

@section links
{
    <link rel="canonical" href="@canonical" />
}


@if (Model.ProductType != ProductType.Cleaning)
{

    <style>
        .table-bordered td {
            border: 1px solid #000000;
        }
    </style>
    <div class="container">
        <div class="pl-4 pt-5">
            <h3>
                @Html.DisplayFor(model => model.Title)
                @if (!string.IsNullOrEmpty(Model.ButtonDescriptionName))
                {
                    <input type="button" class="btn btn-info" onClick="window.open('@Url.Action("DisplayPdf", "Productions", new {id = Model.Id})', target='_blank')" value='@Html.DisplayFor(modelItem => Model.ButtonDescriptionName)' />
                }
            </h3>
            <hr />
        </div>
        <div class="col-lg-5 float-lg-left">
            <img class="card-img-top" src="@Model.Photo" alt="">
        </div>
        <div class="pl-4">
            @Html.Raw(Model.Description)
        </div>

        <div class="cooperation-container">
            <section class="cooperation">
                <a href="/Company#feedback">
                    <img src="/Pictures/Cooperation.png" alt="Торговый дом Нептун">
                    <article>
                        <p>
                            Задайте интересующие вопросы и в ближайшее время мы свяжемся с вами.
                        </p>
                    </article>
                </a>
            </section>
        </div>

    </div>
}
else
{
    Layout = "";
    @Html.Raw(Model.Description);
}